version: '3.8'

x-common-variables: &common-variables
  MYSQL_HOST: localhost
  MYSQL_DATABASE: books
  MYSQL_PASSWORD: 123456
  MYSQL_ROOT_PASSWORD: 123456

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      DB_PORT: 3306
      DB_SYNC: true
      DB_NAME: remitano-test
      MYSQL_USER: root

  client:
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_API_URL: http://localhost:3000
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
