export enum ENV_CONST {
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',

  JWT_TOKEN_EXPIRE = 'JWT_TOKEN_EXPIRE',
  JWT_SEC = 'JWT_SEC',
}
