export enum ENV_CONST {
  MYSQL_HOST = 'MYSQL_HOST',
  DB_PORT = 'DB_PORT',
  MYSQL_USER = 'MYSQL_USER',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  DB_NAME = 'DB_NAME',

  JWT_TOKEN_EXPIRE = 'JWT_TOKEN_EXPIRE',
  JWT_SEC = 'JWT_SEC',
}
